# Generated by Django 4.2.11 on 2024-04-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_residents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residents',
            name='careOf',
        ),
    ]
