# Generated by Django 4.2.11 on 2024-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_caretaker_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
