# Generated by Django 4.2.11 on 2024-04-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_weightchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightchart',
            name='login',
        ),
        migrations.AddField(
            model_name='weightchart',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.residents'),
        ),
    ]
