# Generated by Django 4.2.11 on 2024-04-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_weightchart_login_weightchart_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('meal', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.residents')),
            ],
        ),
    ]
