# Generated by Django 4.2.9 on 2024-04-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='times',
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='bf_af',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
