# Generated by Django 4.2.9 on 2024-04-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_medicine_quantity_remove_medicine_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=100, null=True)),
                ('disLikes', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=100, null=True)),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.residents')),
            ],
        ),
    ]
