# Generated by Django 4.2.11 on 2024-04-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_dislikes_careplan_likeordislike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.residents')),
            ],
        ),
    ]
