# Generated by Django 4.2.11 on 2024-04-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_emergencysituation_desc_emergencysituation_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencysituation',
            old_name='desc',
            new_name='reply',
        ),
    ]
